$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1.5
        },
        360:{
            items:2.1
        },
        500:{
            items:3
        },
        600:{
            items:3.5
        },
        800:{
            items:4
        },
        900:{
            items:5
        },
        
    }
})